classDiagram
direction TB

class Fordringshaver["Fordringshaver"]
class Fordring["Fordring"]
class Skyldner["Skyldner"]
class Kravgrundlag["Kravgrundlag"]
class Underretning["Underretning"]
class PaaKrav["Påkrav"]
class Rykker["Rykker"]
class Betalingsfrist["Betalingsfrist"]
class Restance["Restance"]
class Indsigelse["Indsigelse"]
class OverdragelseTilInddrivelse["Overdragelse til inddrivelse"]
class Restanceinddrivelsesmyndighed["Restanceinddrivelsesmyndighed"]
class Inddrivelsesskridt["Inddrivelsesskridt"]

Fordringshaver --> Fordring : har
Fordring --> Skyldner : er rettet mod
Fordring --> Kravgrundlag : er begrundet i
Fordringshaver --> Underretning : giver
Underretning --> Skyldner : tilgår
Fordringshaver --> PaaKrav : fremsender
PaaKrav --> Fordring : vedrører
PaaKrav --> Skyldner : rettes mod
Fordringshaver --> Rykker : fremsender
Rykker --> Fordring : vedrører
Fordring --> Betalingsfrist : har
Fordring --> Restance : kan overgå til
Skyldner --> Indsigelse : fremsætter
Indsigelse --> Fordring : vedrører
Fordringshaver --> OverdragelseTilInddrivelse : foretager
Restance --> OverdragelseTilInddrivelse : omfatter
OverdragelseTilInddrivelse --> Restanceinddrivelsesmyndighed : sker til
Restanceinddrivelsesmyndighed --> Inddrivelsesskridt : iværksætter
Inddrivelsesskridt --> Fordring : vedrører
