apiVersion: v1
kind: Service
metadata:
  name: opendebt-creditor-service
  namespace: opendebt
  labels:
    app: opendebt-creditor-service
spec:
  type: ClusterIP
  ports:
    - port: 8092
      targetPort: 8092
      protocol: TCP
      name: http
  selector:
    app: opendebt-creditor-service
