apiVersion: v1
kind: Service
metadata:
  name: opendebt-letter-service
  namespace: opendebt
  labels:
    app: opendebt-letter-service
spec:
  type: ClusterIP
  ports:
    - port: 8084
      targetPort: 8084
      protocol: TCP
      name: http
  selector:
    app: opendebt-letter-service
