apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opendebt-production

resources:
  - ../../base

nameSuffix: -production

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
    target:
      kind: Deployment
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "1Gi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "2Gi"
    target:
      kind: Deployment

configMapGenerator:
  - name: opendebt-config
    behavior: merge
    literals:
      - SPRING_PROFILES_ACTIVE=production
      - KEYCLOAK_ISSUER_URI=https://keycloak.opendebt.dk/realms/opendebt

images:
  - name: opendebt/opendebt-case-service
    newTag: latest
  - name: opendebt/opendebt-debt-service
    newTag: latest
  - name: opendebt/opendebt-payment-service
    newTag: latest
  - name: opendebt/opendebt-letter-service
    newTag: latest
  - name: opendebt/opendebt-person-registry
    newTag: latest
  - name: opendebt/opendebt-creditor-service
    newTag: latest
  - name: opendebt/opendebt-creditor-portal
    newTag: latest
  - name: opendebt/opendebt-caseworker-portal
    newTag: latest
  - name: opendebt/opendebt-citizen-portal
    newTag: latest
