apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opendebt

resources:
  - namespace.yaml
  - configmap.yaml
  - service-account.yaml
  - case-service/
  - debt-service/
  - payment-service/
  - letter-service/
  - person-registry/
  - creditor-service/
  - creditor-portal/
  - caseworker-portal/
  - citizen-portal/
  - pgbackrest/
  - keycloak-backup/

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: opendebt
