apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opendebt-staging

resources:
  - ../../base

nameSuffix: -staging

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment

configMapGenerator:
  - name: opendebt-config
    behavior: merge
    literals:
      - SPRING_PROFILES_ACTIVE=staging
      - KEYCLOAK_ISSUER_URI=https://keycloak-staging.opendebt.dk/realms/opendebt

images:
  - name: opendebt/opendebt-case-service
    newTag: staging
  - name: opendebt/opendebt-debt-service
    newTag: staging
  - name: opendebt/opendebt-payment-service
    newTag: staging
  - name: opendebt/opendebt-letter-service
    newTag: staging
  - name: opendebt/opendebt-person-registry
    newTag: staging
  - name: opendebt/opendebt-creditor-service
    newTag: staging
  - name: opendebt/opendebt-creditor-portal
    newTag: staging
  - name: opendebt/opendebt-caseworker-portal
    newTag: staging
  - name: opendebt/opendebt-citizen-portal
    newTag: staging
